@startuml
class MoodComments {
- RecyclerView recyclerView
~ NavigationBarView navigationBar
- BottomNavBarController navBarController
- ImageView imageMoodIcon
- TextView tvMoodState
- MoodEventProvider provider
- CommentProvider commentProvider
- UserProvider userProvider
- List<MoodEvent> moods
- ListenerRegistration snapshotListener
- FirebaseFirestore db
- String moodEventId
- String sourceScreen
- String userId
- String username
- TextInputLayout searchInputLayout
- TextInputEditText searchInput
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void setupCommentSendButton()
- void submitComment(String)
- void fetchComments()
- void fetchMoodDetails(String)
- void bindMoodData(MoodEvent)
- void refreshComments()
- void handleBackButton()
+ void onItemClick(String)
}


class MoodEventFilter {
- Query allMoodEvents
- Set<Emotion> emotions
- String userId
- Date startDate
- Date endDate
- String sortField
- Query.Direction sortDirection
- Double latitude
- Double longitude
- Double radius
+ MoodEventFilter addEmotion(Emotion)
+ MoodEventFilter addEmotions(Set<Emotion>)
+ MoodEventFilter setEmotions(Set<Emotion>)
+ MoodEventFilter setLocation(Double,Double,double)
+ MoodEventFilter setDateRange(Date,Date)
+ MoodEventFilter setSortField(String,Query.Direction)
+ MoodEventFilter setUser(String)
+ int count()
+ void clearFilters()
+ String getSummary()
+ Query buildQuery()
}


class MoodHistoryAdapter {
- List<MoodEvent> moods
- SimpleDateFormat dateFormat
- OnItemClickListener listener
+ void setMoods(List<MoodEvent>)
+ MoodViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MoodViewHolder,int)
+ int getItemCount()
+ List<MoodEvent> getItems()
}


interface MoodHistoryAdapter$OnItemClickListener {
~ void onItemClick(String)
}

class MoodHistoryAdapter$MoodViewHolder {
+ TextView textDate
+ TextView textMoodEventNumber
}

class FilterBarFragment {
- MoodEventFilter moodEventFilter
- Set<Emotion> selectedEmotions
- OnFilterChangedListener listener
- TextInputEditText searchEditText
- MaterialButton filterEmotion
- MaterialButton filterCountAndEdit
- MaterialButton filterTimeRange
- MaterialButton filterLocation
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ MoodEventFilter getMoodEventFilter()
+ void setOnFilterChangedListener(OnFilterChangedListener)
- void notifyFilterChanged()
- void resetTime(Calendar)
}


interface FilterBarFragment$OnFilterChangedListener {
~ void onFilterChanged(MoodEventFilter)
}

class MoodIconUtil {
+ {static} int getMoodIconResource(String)
}

class MoodEventForm {
- Button addLocation
- EmotionPickerFragment emotionPickerFragment
- AutoCompleteTextView situationAutoComplete
- TextInputEditText reasonEditText
- Double currentLatitude
- Double currentLongitude
- Bitmap photo
- ImageButton photoButton
- Button photoResetButton
- TextView photoButtonError
- MaterialButtonToggleGroup visibilityToggle
- MoodEventFormSubmitCallback callback
- void resetPhoto()
- void setImageFromBitmap(Bitmap)
- void updateResetPhotoVisibility()
+ void onSubmit(MoodEventFormSubmitCallback)
+ void bind(MoodEventDetails)
- void resetPhotoButtonError()
- MoodEventDetails validateFields()
- void handleSubmit(View)
+ void onViewCreated(View,Bundle)
+ void onLocationUpdated(Double,Double)
}


interface MoodEventForm$MoodEventFormSubmitCallback {
~ void handleSubmit(MoodEventDetails)
}

class MoodEventForm$MoodEventDetails {
~ String username
~ Emotion emotion
~ String socialSituation
~ String reason
~ Double lat
~ Double lon
~ Bitmap photo
~ MoodEventVisibility visibility
+ MoodEvent toMoodEvent(String)
}


class LocationFragment {
- LocationUpdateListener updateListener
- FusedLocationProviderClient fusedLocationClient
- Button requestLocationButton
- Double latitude
- Double longitude
- ActivityResultLauncher<String> requestPermissionLauncher
- LocationUpdateListener listener
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onAttach(Context)
- void checkLocationAndRequestPermission()
- boolean isLocationEnabled()
- void handleLocationServicesDisabled()
- void requestLocationPermission()
- void getLastLocation()
- void requestNewLocation()
- void handleLocationSuccess(Location)
+ void saveMoodEventWithoutLocation()
+ void setUpdateListener(LocationUpdateListener)
}


class DeleteDialogFragment {
- FirebaseFirestore db
- DeleteDialogListener listener
+ void setDeleteDialogListener(DeleteDialogListener)
+ DeleteDialogListener getDeleteDialogListener()
+ void onAttach(Context)
+ Dialog onCreateDialog(Bundle)
}


interface DeleteDialogFragment$DeleteDialogListener {
~ void onDeleteConfirmed()
}

class CommentProvider {
- CollectionReference collection
- {static} CommentProvider instance
+ {static} CommentProvider getInstance()
+ Task<Void> insertComment(Comment)
+ Task<List<Comment>> getCommentsByMoodEventId(String)
}


class MoodDetails {
- MaterialToolbar toolbar
- ImageView imageMoodIcon
- TextView tvMoodState
- Chip tvUsernameDisplay
- Button btnEditMood
- Button btnDeleteMood
- Button btnMoodComments
- ImageView visibilityIcon
- FirebaseFirestore db
- MoodEventProvider provider
- String moodEventId
- String sourceScreen
- String userId
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void fetchMoodDetails(String)
- void bindMoodData(MoodEvent)
- void handleOwnershipUI(String)
- void handleBackButton()
+ void onDeleteConfirmed()
}


class MyProfile {
~ FirebaseAuth auth
~ FirebaseUser user
~ TextView usernameText
~ ImageView profileImage
~ Button signOutButton
~ NavigationBarView navigationBarView
~ BottomNavBarController navBarController
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void onClickSignOut(View)
}


class BottomNavBarController {
- NavigationBarView navigationBar
- View view
+ void bind(View)
+ boolean onNavigationItemSelected(MenuItem)
}


enum Emotion {
+  ANGER
+  CONFUSION
+  DISGUST
+  FEAR
+  HAPPINESS
+  SADNESS
+  SHAME
+  SURPRISE
+  ERROR
+ {abstract}int getIconRes()
+ {abstract}int getColorRes()
+ {static} Emotion fromString(String)
}


class AuthSignUp {
- long lastClickTime
- FirebaseAuth auth
- FirebaseFirestore db
- MaterialToolbar topAppBar
- EditText usernameEditText
- EditText emailEditText
- EditText passwordEditText
- TextInputLayout usernameLayout
- TextInputLayout emailLayout
- TextInputLayout passwordLayout
- TextView generalErrorText
- Button signUpButton
- void validateFieldsAndSignUp(OnValidationCompleteListener)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void signUpUser(SignUpDetails)
- void deleteAuthUserIfExists()
- void checkUsernameUnique(String,OnUsernameCheckListener)
- void setGeneralError(Exception)
}


class AuthSignUp$SignUpDetails {
~ String userName
~ String email
~ String password
}

interface AuthSignUp$OnValidationCompleteListener {
~ void onValidationComplete(SignUpDetails)
}

interface AuthSignUp$OnUsernameCheckListener {
~ void onCheckComplete(boolean)
}

class CreateMoodEvent {
- NavController navController
- BottomNavBarController navBarController
- FirebaseUser currentUser
- MoodEventProvider provider
- void handleSubmit(MoodEventForm.MoodEventDetails)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class EmotionPickerFragment {
- ArrayList<EmotionToggle> toggles
- TextView errorView
- Emotion selected
- OnSelectEmotionListener onSelectEmotionListener
- String error
+ void onViewCreated(View,Bundle)
- void updateToggleTints()
- void updateError()
- View.OnClickListener createToggleClickListener(EmotionToggle)
+ Emotion getSelected()
+ void setSelected(Emotion)
+ void setOnSelectEmotionListener(OnSelectEmotionListener)
+ String getError()
+ void setError(String)
}


class EmotionPickerFragment$EmotionToggle {
~ MaterialButton button
~ Emotion emotion
}

class EmotionToggleConfig {
~ int id
~ Emotion emotion
}

interface EmotionPickerFragment$OnSelectEmotionListener {
~ void onSelectEmotion(Emotion)
}

class User {
- String name
- boolean followed
+ String getName()
+ boolean isFollowed()
}


class RequestFragment {
- String requestType
- String username
- FirebaseFirestore db
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void acceptFollowRequest(String)
- void denyFollowRequest(String)
- void confirmUnfollow(String)
}


class LocationHandler {
- {static} String TAG
- Context context
- FusedLocationProviderClient fusedLocationClient
+ void fetchLocation(OnLocationObtainedListener)
- void requestNewLocation(OnLocationObtainedListener)
- boolean isLocationEnabled()
}


interface LocationHandler$OnLocationObtainedListener {
~ void onLocationObtained(double,double)
~ void onLocationFailed(String)
}

class UploadPhotoFragment {
~ UploadPhotoListener uploadPhotoListener
- ActivityResultLauncher<Intent> pickImageLauncher
- String currentPhotoPath
- ActivityResultLauncher<Intent> captureImageLauncher
+ void setUploadPhotoListener(UploadPhotoListener)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- Bitmap loadBitmapFromUri(Uri)
- void openImagePicker()
- void openImageCapture()
}


interface UploadPhotoFragment$UploadPhotoListener {
~ void onUpload(Bitmap)
}

class MoodAdapter {
- List<MoodEvent> moods
- OnMoodClickListener onMoodClickListener
- UserProvider userProvider
+ void setOnMoodClickListener(OnMoodClickListener)
+ void setMoods(List<MoodEvent>)
+ MoodViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MoodViewHolder,int)
+ int getItemCount()
}


interface MoodAdapter$OnMoodClickListener {
~ void onViewDetails(MoodEvent)
~ void onViewComments(MoodEvent)
}

class MoodAdapter$MoodViewHolder {
~ ImageView moodImageView
~ TextView moodTypeTextView
~ TextView dayTimeTextView
~ View viewDetailsButton
~ TextView usernameText
~ ImageView purple_icon_arrow
~ ImageView comments_bubble
~ View commentLayout
~ ImageView visibilityIcon
}

class CommentAdapter {
- List<Comment> comments
+ CommentViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(CommentViewHolder,int)
+ int getItemCount()
+ void setComments(List<Comment>)
}


class CommentAdapter$CommentViewHolder {
- TextView commentText
- TextView userNameText
- TextView timestampText
+ void bind(Comment)
}


class MoodHistory {
- RecyclerView recyclerView
~ NavigationBarView navigationBar
- BottomNavBarController navBarController
+ MoodHistoryAdapter adapter
- MoodEventProvider provider
- ListenerRegistration snapshotListener
- FilterBarFragment searchNFilterFragment
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void onResume()
+ void onPause()
+ void onItemClick(String)
- void handleBackButton()
}


class FollowRequestAdapter {
- List<String> items
- FollowRequestsFragment fragment
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class FollowRequestAdapter$ViewHolder {
~ ImageView uid
~ TextView requestMessage
~ Button acceptButton
}

class UserProvider {
- FirebaseFirestore db
- {static} UserProvider instance
+ {static} UserProvider getInstance()
+ Task<String> getUsername(String)
+ Task<List<User>> fetchFollowers(String)
+ Task<List<User>> fetchFollowing(String)
+ void addSnapshotListenerForUser(String,EventListener<DocumentSnapshot>)
+ Task<String> fetchUsername(String)
}


class HomeFeed {
~ FirebaseAuth auth
~ FirebaseUser user
~ MoodEventProvider provider
~ FilterBarFragment searchNFilterFragment
~ NavigationBarView navigationBar
~ BottomNavBarController navBarController
~ RecyclerView moodRecyclerView
~ MoodAdapter moodAdapter
+ {static} List<MoodEvent> currentFilteredList
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class Comment {
- String id
- String uid
- String username
- String moodEventId
- Date created
- String commentText
+ String toString()
+ String getId()
+ void setId(String)
+ String getUid()
+ void setUid(String)
+ String getUsername()
+ void setUsername(String)
+ Date getCreated()
+ void setCreated(Date)
+ String getCommentText()
+ void setCommentText(String)
+ String getMoodEventId()
+ void setMoodEventId(String)
+ long getTimestamp()
}


class AuthSignIn {
- FirebaseAuth auth
- MaterialToolbar topAppBar
- EditText emailEditText
- EditText passwordEditText
- TextInputLayout emailLayout
- TextInputLayout passwordLayout
- Button signInButton
- TextView generalErrorText
- SignInDetails validateFields()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- boolean checkEmailValid(String)
- boolean checkPasswordValid(String)
- void setGeneralError(Exception)
}


class AuthSignIn$SignInDetails {
~ String email
~ String password
}

interface LocationUpdateListener {
~ void onLocationUpdated(Double,Double)
}

class FollowRequestsFragment {
- FirebaseFirestore db
- List<String> requestList
- FollowRequestAdapter adapter
- BottomNavBarController navBarController
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void accept(String)
+ void deny(String)
}


class AuthHome {
~ FirebaseAuth auth
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class EditMoodEvent {
- String moodEventId
- NavController navController
- BottomNavBarController navBarController
- FirebaseUser currentUser
- MoodEventProvider provider
- void handleSubmit(MoodEventForm.MoodEventDetails)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class MoodEvent {
- String id
- String uid
- String username
- Date created
- Emotion emotion
- String socialSituation
- String reason
- Bitmap photo
- Double latitude
- Double longitude
- MoodEventVisibility visibility
+ String getId()
+ void setId(String)
+ String getUid()
+ void setUid(String)
+ String getUsername()
+ void setUsername(String)
+ Date getCreated()
+ void setCreated(Date)
+ Emotion getEmotion()
+ void setEmotion(String)
+ String getSocialSituation()
+ void setSocialSituation(String)
+ String getReason()
+ void setReason(String)
+ Bitmap getPhoto()
+ void setPhoto(Bitmap)
+ List<Integer> getPhotoBytes()
+ void setPhotoBytes(List<Integer>)
+ Double getLatitude()
+ void setLatitude(Double)
+ Double getLongitude()
+ void setLongitude(Double)
+ long getTimestamp()
+ MoodEventVisibility getVisibility()
+ void setVisibility(MoodEventVisibility)
}

class FollowProvider {
- {static} FollowProvider instance
- FirebaseFirestore db
+ {static} FollowProvider getInstance()
+ Task<Void> sendRequest(String,String)
+ Task<Void> deleteRequest(String,String)
+ Task<Void> acceptRequest(String,String)
+ Task<List<User>> fetchFollowers(String)
+ Task<List<User>> fetchFollowing(String)
+ Task<Void> unfollow(String,String)
+ Task<Boolean> isFollowing(String,String)
+ Task<Boolean> hasPendingRequest(String,String)
}


class PhotoUtils {
+ {static} List<Integer> compressPhoto(Bitmap)
+ {static} Bitmap decodePhoto(List<Integer>)
}

class FollowingFragment {
- FollowingAdapter adapter
- List<User> followingList
- BottomNavBarController navBarController
- UserProvider userProvider
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void fetchFollowing()
}


class FollowingFragment$FollowingAdapter {
- List<User> users
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class FollowingFragment$FollowingAdapter$ViewHolder {
~ ShapeableImageView avatarImageView
~ TextView usernameTextView
}

class OtherUserProfile {
- {static} String TAG
- String uidToLoad
- TextView usernameText
- TextView emailText
- MaterialToolbar toolbar
- Button followButton
- Button followersButton
- Button followingButton
- RecyclerView publicMoodsRecyclerView
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void setupFollowButtonLogic()
- void setupPublicMoodRecycler(View)
}


class MoodMap {
- NavigationBarView navigationBarView
- BottomNavBarController navBarController
- MoodEventProvider moodEventProvider
- GoogleMap moodMap
- Map<Marker,MoodEvent> markerToMoodMap
- {static} List<MoodEvent> sharedMoodEvents
- UserProvider userProvider
+ {static} void setSharedMoodEvents(List<MoodEvent>)
+ {static} List<MoodEvent> getSharedMoodEvents()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void onMapReady(GoogleMap)
+ void loadMoodEventsOnMap(List<MoodEvent>)
- float getEmotionColour(String)
}


enum MoodEventVisibility {
+  PUBLIC
+  PRIVATE
}

class MoodEventProvider {
- CollectionReference collection
- FirebaseAuth auth
- {static} MoodEventProvider instance
+ {static} MoodEventProvider getInstance()
+ Task<Void> insertMoodEvent(MoodEvent)
+ Task<Void> updateMoodEvent(String,MoodEvent)
+ Task<MoodEvent> getMoodEvent(String)
+ Query getAll()
}


class FollowersFragment {
- FollowersAdapter adapter
- List<User> followersList
- BottomNavBarController navBarController
- UserProvider userProvider
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class FollowersFragment$FollowersAdapter {
- List<User> users
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class FollowersFragment$FollowersAdapter$ViewHolder {
~ ShapeableImageView avatarImageView
~ TextView usernameTextView
}



MoodHistoryAdapter +.. MoodHistoryAdapter$OnItemClickListener
MoodHistoryAdapter +.. MoodHistoryAdapter$MoodViewHolder
FilterBarFragment +.. FilterBarFragment$OnFilterChangedListener
LocationUpdateListener <|.. MoodEventForm
MoodEventForm +.. MoodEventForm$MoodEventFormSubmitCallback
MoodEventForm +.. MoodEventForm$MoodEventDetails
DeleteDialogFragment +.. DeleteDialogFragment$DeleteDialogListener
AuthSignUp +.. AuthSignUp$SignUpDetails
AuthSignUp +.. AuthSignUp$OnValidationCompleteListener
AuthSignUp +.. AuthSignUp$OnUsernameCheckListener
EmotionPickerFragment +.. EmotionPickerFragment$EmotionToggle
EmotionPickerFragment +.. EmotionPickerFragment$OnSelectEmotionListener
LocationHandler +.. LocationHandler$OnLocationObtainedListener
UploadPhotoFragment +.. UploadPhotoFragment$UploadPhotoListener
MoodAdapter +.. MoodAdapter$OnMoodClickListener
MoodAdapter +.. MoodAdapter$MoodViewHolder
CommentAdapter +.. CommentAdapter$CommentViewHolder
FollowRequestAdapter +.. FollowRequestAdapter$ViewHolder
AuthSignIn +.. AuthSignIn$SignInDetails
FollowingFragment +.. FollowingFragment$FollowingAdapter
FollowingFragment$FollowingAdapter +.. FollowingFragment$FollowingAdapter$ViewHolder
FollowersFragment +.. FollowersFragment$FollowersAdapter
FollowersFragment$FollowersAdapter +.. FollowersFragment$FollowersAdapter$ViewHolder
@enduml