@startuml
class com.kernelcrew.moodapp.ui.EditMoodEvent {
- String moodEventId
- NavController navController
- BottomNavBarController navBarController
- FirebaseUser currentUser
- MoodEventProvider provider
- void handleSubmit(MoodEventForm.MoodEventDetails)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class com.kernelcrew.moodapp.data.MoodEventFilter {
- CollectionReference collectionReference
- Set<Emotion> emotions
- String userId
- Date startDate
- Date endDate
- String sortField
- Query.Direction sortDirection
- Double latitude
- Double longitude
- Double radius
+ MoodEventFilter addEmotion(Emotion)
+ MoodEventFilter addEmotions(Set<Emotion>)
+ MoodEventFilter setEmotions(Set<Emotion>)
+ MoodEventFilter setLocation(Double,Double,double)
+ MoodEventFilter setDateRange(Date,Date)
+ MoodEventFilter setSortField(String,Query.Direction)
+ MoodEventFilter setUser(String)
+ int count()
+ void clearFilters()
+ String getSummary()
+ Query buildQuery()
}


class com.kernelcrew.moodapp.ui.components.EmotionPickerFragment {
- ArrayList<EmotionToggle> toggles
- TextView errorView
- Emotion selected
- OnSelectEmotionListener onSelectEmotionListener
- String error
+ void onViewCreated(View,Bundle)
- void updateToggleTints()
- void updateError()
- View.OnClickListener createToggleClickListener(EmotionToggle)
+ Emotion getSelected()
+ void setSelected(Emotion)
+ void setOnSelectEmotionListener(OnSelectEmotionListener)
+ String getError()
+ void setError(String)
}


class com.kernelcrew.moodapp.ui.components.EmotionPickerFragment$EmotionToggle {
~ MaterialButton button
~ Emotion emotion
}

class com.kernelcrew.moodapp.ui.components.EmotionToggleConfig {
~ int id
~ Emotion emotion
}

interface com.kernelcrew.moodapp.ui.components.EmotionPickerFragment$OnSelectEmotionListener {
~ void onSelectEmotion(Emotion)
}

class com.kernelcrew.moodapp.ui.MainActivity {
# void onCreate(Bundle)
}

class com.kernelcrew.moodapp.data.Comment {
- String id
- String uid
- String username
- String moodEventId
- Date created
- String commentText
+ String toString()
+ String getId()
+ void setId(String)
+ String getUid()
+ void setUid(String)
+ String getUsername()
+ void setUsername(String)
+ Date getCreated()
+ void setCreated(Date)
+ String getCommentText()
+ void setCommentText(String)
+ String getMoodEventId()
+ void setMoodEventId(String)
+ long getTimestamp()
}


class com.kernelcrew.moodapp.ui.DeleteDialogFragment {
- FirebaseFirestore db
- DeleteDialogListener listener
+ void setDeleteDialogListener(DeleteDialogListener)
+ DeleteDialogListener getDeleteDialogListener()
+ void onAttach(Context)
+ Dialog onCreateDialog(Bundle)
}


interface com.kernelcrew.moodapp.ui.DeleteDialogFragment$DeleteDialogListener {
~ void onDeleteConfirmed()
}

class com.kernelcrew.moodapp.ui.MoodHistoryAdapter {
- List<MoodEvent> moods
- SimpleDateFormat dateFormat
- OnItemClickListener listener
+ void setMoods(List<MoodEvent>)
+ MoodViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MoodViewHolder,int)
+ int getItemCount()
+ List<MoodEvent> getItems()
}


interface com.kernelcrew.moodapp.ui.MoodHistoryAdapter$OnItemClickListener {
~ void onItemClick(String)
}

class com.kernelcrew.moodapp.ui.MoodHistoryAdapter$MoodViewHolder {
+ TextView textDate
+ TextView textMoodEventNumber
}

enum com.kernelcrew.moodapp.data.MoodEventVisibility {
+  PUBLIC
+  PRIVATE
}

class com.kernelcrew.moodapp.data.LocationHandler {
- {static} String TAG
- Context context
- FusedLocationProviderClient fusedLocationClient
+ void fetchLocation(OnLocationObtainedListener)
- void requestNewLocation(OnLocationObtainedListener)
- boolean isLocationEnabled()
}


interface com.kernelcrew.moodapp.data.LocationHandler$OnLocationObtainedListener {
~ void onLocationObtained(double,double)
~ void onLocationFailed(String)
}

class com.kernelcrew.moodapp.data.MoodEvent {
- String id
- String uid
- String username
- Date created
- Emotion emotion
- String socialSituation
- String reason
- Bitmap photo
- Double latitude
- Double longitude
- MoodEventVisibility visibility
+ String getId()
+ void setId(String)
+ String getUid()
+ void setUid(String)
+ String getUsername()
+ void setUsername(String)
+ Date getCreated()
+ void setCreated(Date)
+ Emotion getEmotion()
+ void setEmotion(String)
+ String getSocialSituation()
+ void setSocialSituation(String)
+ String getReason()
+ void setReason(String)
+ Bitmap getPhoto()
+ void setPhoto(Bitmap)
+ List<Integer> getPhotoBytes()
+ void setPhotoBytes(List<Integer>)
+ Double getLatitude()
+ void setLatitude(Double)
+ Double getLongitude()
+ void setLongitude(Double)
+ long getTimestamp()
+ MoodEventVisibility getVisibility()
+ void setVisibility(MoodEventVisibility)
}


class com.kernelcrew.moodapp.data.MoodEventProvider {
- CollectionReference collection
- FirebaseAuth auth
- {static} MoodEventProvider instance
+ {static} MoodEventProvider getInstance()
+ {static} void setInstance(MoodEventProvider)
+ Task<Void> insertMoodEvent(MoodEvent)
+ Task<Void> updateMoodEvent(String,MoodEvent)
+ Task<MoodEvent> getMoodEvent(String)
+ void addSnapshotListener(EventListener<QuerySnapshot>)
+ Task<QuerySnapshot> getMoodEvents()
+ CollectionReference getCollectionReference()
+ ListenerRegistration addUserFilteredSnapshotListener(EventListener<QuerySnapshot>)
}


class com.kernelcrew.moodapp.data.CommentProvider {
- CollectionReference collection
- {static} CommentProvider instance
+ {static} CommentProvider getInstance()
+ Task<Void> insertComment(Comment)
+ Task<List<Comment>> getCommentsByMoodEventId(String)
}


class com.kernelcrew.moodapp.ui.CommentAdapter {
- List<Comment> comments
+ CommentViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(CommentViewHolder,int)
+ int getItemCount()
+ void setComments(List<Comment>)
}


class com.kernelcrew.moodapp.ui.CommentAdapter$CommentViewHolder {
- TextView commentText
- TextView userNameText
- TextView timestampText
+ void bind(Comment)
}


class com.kernelcrew.moodapp.ui.MyProfile {
~ FirebaseAuth auth
~ FirebaseUser user
~ TextView usernameText
~ ImageView profileImage
~ Button signOutButton
~ NavigationBarView navigationBarView
~ BottomNavBarController navBarController
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void onClickSignOut(View)
}


class com.kernelcrew.moodapp.ui.CreateMoodEvent {
- NavController navController
- BottomNavBarController navBarController
- FirebaseUser currentUser
- MoodEventProvider provider
- void handleSubmit(MoodEventForm.MoodEventDetails)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class com.kernelcrew.moodapp.ui.AuthSignUp {
- long lastClickTime
- FirebaseAuth auth
- FirebaseFirestore db
- MaterialToolbar topAppBar
- EditText usernameEditText
- EditText emailEditText
- EditText passwordEditText
- TextInputLayout usernameLayout
- TextInputLayout emailLayout
- TextInputLayout passwordLayout
- TextView generalErrorText
- Button signUpButton
- void validateFieldsAndSignUp(OnValidationCompleteListener)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void signUpUser(SignUpDetails)
- void deleteAuthUserIfExists()
- void checkUsernameUnique(String,OnUsernameCheckListener)
- void setGeneralError(Exception)
}


class com.kernelcrew.moodapp.ui.AuthSignUp$SignUpDetails {
~ String userName
~ String email
~ String password
}

interface com.kernelcrew.moodapp.ui.AuthSignUp$OnValidationCompleteListener {
~ void onValidationComplete(SignUpDetails)
}

interface com.kernelcrew.moodapp.ui.AuthSignUp$OnUsernameCheckListener {
~ void onCheckComplete(boolean)
}

class com.kernelcrew.moodapp.data.UserProvider {
- FirebaseFirestore db
- {static} UserProvider instance
+ {static} UserProvider getInstance()
+ Task<String> getUsername(String)
+ Task<List<User>> fetchFollowers(String)
+ Task<List<User>> fetchFollowing(String)
+ void addSnapshotListenerForUser(String,EventListener<DocumentSnapshot>)
+ Task<String> fetchUsername(String)
}


class com.kernelcrew.moodapp.ui.BottomNavBarController {
- NavigationBarView navigationBar
- View view
+ void bind(View)
+ boolean onNavigationItemSelected(MenuItem)
}


class com.kernelcrew.moodapp.ui.MoodAdapter {
- List<MoodEvent> moods
- OnMoodClickListener onMoodClickListener
- UserProvider userProvider
+ void setOnMoodClickListener(OnMoodClickListener)
+ void setMoods(List<MoodEvent>)
+ MoodViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(MoodViewHolder,int)
+ int getItemCount()
}


interface com.kernelcrew.moodapp.ui.MoodAdapter$OnMoodClickListener {
~ void onViewDetails(MoodEvent)
~ void onViewComments(MoodEvent)
}

class com.kernelcrew.moodapp.ui.MoodAdapter$MoodViewHolder {
~ ImageView moodImageView
~ TextView moodTypeTextView
~ TextView dayTimeTextView
~ View viewDetailsButton
~ TextView usernameText
~ ImageView purple_icon_arrow
~ ImageView comments_bubble
~ View commentLayout
}

class com.kernelcrew.moodapp.ui.FollowRequestsFragment {
- FirebaseFirestore db
- List<String> requestList
- FollowRequestAdapter adapter
- BottomNavBarController navBarController
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void accept(String)
+ void deny(String)
}


class com.kernelcrew.moodapp.ui.components.UploadPhotoFragment {
~ UploadPhotoListener uploadPhotoListener
- ActivityResultLauncher<Intent> pickImageLauncher
- String currentPhotoPath
- ActivityResultLauncher<Intent> captureImageLauncher
+ void setUploadPhotoListener(UploadPhotoListener)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- Bitmap loadBitmapFromUri(Uri)
- void openImagePicker()
- void openImageCapture()
}


interface com.kernelcrew.moodapp.ui.components.UploadPhotoFragment$UploadPhotoListener {
~ void onUpload(Bitmap)
}

class com.kernelcrew.moodapp.ui.HomeFeed {
~ FirebaseAuth auth
~ FirebaseUser user
~ MoodEventProvider provider
~ FilterBarFragment searchNFilterFragment
~ NavigationBarView navigationBar
~ BottomNavBarController navBarController
~ RecyclerView moodRecyclerView
~ MoodAdapter moodAdapter
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class com.kernelcrew.moodapp.ui.FollowersFragment {
- FollowersAdapter adapter
- List<User> followersList
- BottomNavBarController navBarController
- UserProvider userProvider
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter {
- List<User> users
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter$ViewHolder {
~ ShapeableImageView avatarImageView
~ TextView usernameTextView
}

class com.kernelcrew.moodapp.ui.OtherUserProfile {
- {static} String TAG
- String uidToLoad
- TextView usernameText
- TextView emailText
- MaterialToolbar toolbar
- Button followButton
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
}


class com.kernelcrew.moodapp.ui.AuthSignIn {
- FirebaseAuth auth
- MaterialToolbar topAppBar
- EditText emailEditText
- EditText passwordEditText
- TextInputLayout emailLayout
- TextInputLayout passwordLayout
- Button signInButton
- TextView generalErrorText
- SignInDetails validateFields()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- boolean checkEmailValid(String)
- boolean checkPasswordValid(String)
- void setGeneralError(Exception)
}


class com.kernelcrew.moodapp.ui.AuthSignIn$SignInDetails {
~ String email
~ String password
}

class com.kernelcrew.moodapp.ui.MoodDetails {
- MaterialToolbar toolbar
- ImageView imageMoodIcon
- TextView tvMoodState
- Chip tvUsernameDisplay
- Button btnEditMood
- Button btnDeleteMood
- Button btnMoodComments
- FirebaseFirestore db
- MoodEventProvider provider
- String moodEventId
- String sourceScreen
- String userId
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void fetchMoodDetails(String)
- void bindMoodData(MoodEvent)
- void handleOwnershipUI(String)
- void handleBackButton()
+ void onDeleteConfirmed()
}


class com.kernelcrew.moodapp.ui.RequestFragment {
- String requestType
- String username
- FirebaseFirestore db
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void acceptFollowRequest(String)
- void denyFollowRequest(String)
- void confirmUnfollow(String)
}


class com.kernelcrew.moodapp.ui.FollowRequestAdapter {
- List<String> items
- FollowRequestsFragment fragment
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class com.kernelcrew.moodapp.ui.FollowRequestAdapter$ViewHolder {
~ ImageView uid
~ TextView requestMessage
~ Button acceptButton
}

class com.kernelcrew.moodapp.utils.PhotoUtils {
+ {static} List<Integer> compressPhoto(Bitmap)
+ {static} Bitmap decodePhoto(List<Integer>)
}

class com.kernelcrew.moodapp.ui.LocationFragment {
- LocationUpdateListener updateListener
- FusedLocationProviderClient fusedLocationClient
- Button requestLocationButton
- Double latitude
- Double longitude
- ActivityResultLauncher<String> requestPermissionLauncher
- LocationUpdateListener listener
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onAttach(Context)
- void checkLocationAndRequestPermission()
- boolean isLocationEnabled()
- void handleLocationServicesDisabled()
- void requestLocationPermission()
- void getLastLocation()
- void requestNewLocation()
- void handleLocationSuccess(Location)
+ void saveMoodEventWithoutLocation()
+ Double getLatitude()
+ Double getLongitude()
+ void setLocationUpdateListener(LocationUpdateListener)
+ void setUpdateListener(MoodEventForm)
}


class com.kernelcrew.moodapp.ui.FollowingFragment {
- FollowingAdapter adapter
- List<User> followingList
- BottomNavBarController navBarController
- UserProvider userProvider
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void fetchFollowing()
}


class com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter {
- List<User> users
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


class com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter$ViewHolder {
~ ShapeableImageView avatarImageView
~ TextView usernameTextView
}

class com.kernelcrew.moodapp.ui.MoodComments {
- RecyclerView recyclerView
~ NavigationBarView navigationBar
- BottomNavBarController navBarController
- ImageView imageMoodIcon
- TextView tvMoodState
- MoodEventProvider provider
- CommentProvider commentProvider
- UserProvider userProvider
- List<MoodEvent> moods
- ListenerRegistration snapshotListener
- FirebaseFirestore db
- String moodEventId
- String sourceScreen
- String userId
- String username
- TextInputLayout searchInputLayout
- TextInputEditText searchInput
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void setupCommentSendButton()
- void submitComment(String)
- void fetchComments()
- void fetchMoodDetails(String)
- void bindMoodData(MoodEvent)
- void refreshComments()
- void handleBackButton()
+ void onItemClick(String)
}


class com.kernelcrew.moodapp.ui.MoodHistory {
- RecyclerView recyclerView
~ NavigationBarView navigationBar
- BottomNavBarController navBarController
+ MoodHistoryAdapter adapter
- MoodEventProvider provider
- ListenerRegistration snapshotListener
- FilterBarFragment searchNFilterFragment
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void onResume()
+ void onPause()
+ void onItemClick(String)
- void handleBackButton()
}


enum com.kernelcrew.moodapp.data.Emotion {
+  ANGER
+  CONFUSION
+  DISGUST
+  FEAR
+  HAPPINESS
+  SADNESS
+  SHAME
+  SURPRISE
+  ERROR
+ {abstract}int getIconRes()
+ {abstract}int getColorRes()
+ {static} Emotion fromString(String)
}


class com.kernelcrew.moodapp.ui.AuthHome {
~ FirebaseAuth auth
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class com.kernelcrew.moodapp.ui.MoodIconUtil {
+ {static} int getMoodIconResource(String)
}

class com.kernelcrew.moodapp.data.FollowProvider {
- {static} FollowProvider instance
- FirebaseFirestore db
+ {static} FollowProvider getInstance()
+ Task<Void> sendRequest(String,String)
+ Task<Void> deleteRequest(String,String)
+ Task<Void> acceptRequest(String,String)
+ Task<List<User>> fetchFollowers(String)
+ Task<List<User>> fetchFollowing(String)
+ Task<Void> unfollow(String,String)
+ Task<Boolean> isFollowing(String,String)
+ Task<Boolean> hasPendingRequest(String,String)
}


class com.kernelcrew.moodapp.ui.MoodEventForm {
- Button addLocation
- EmotionPickerFragment emotionPickerFragment
- AutoCompleteTextView situationAutoComplete
- TextInputEditText reasonEditText
- Double currentLatitude
- Double currentLongitude
- Bitmap photo
- ImageButton photoButton
- Button photoResetButton
- TextView photoButtonError
- MaterialButtonToggleGroup visibilityToggle
- MoodEventFormSubmitCallback callback
- void resetPhoto()
- void setImageFromBitmap(Bitmap)
- void updateResetPhotoVisibility()
+ void onSubmit(MoodEventFormSubmitCallback)
+ void bind(MoodEventDetails)
- void resetPhotoButtonError()
- MoodEventDetails validateFields()
- void handleSubmit(View)
+ void onViewCreated(View,Bundle)
+ void onLocationUpdated(Double,Double)
}


interface com.kernelcrew.moodapp.ui.MoodEventForm$MoodEventFormSubmitCallback {
~ void handleSubmit(MoodEventDetails)
}

class com.kernelcrew.moodapp.ui.MoodEventForm$MoodEventDetails {
~ String username
~ Emotion emotion
~ String socialSituation
~ String reason
~ Double lat
~ Double lon
~ Bitmap photo
~ MoodEventVisibility visibility
+ MoodEvent toMoodEvent(String)
}


class com.kernelcrew.moodapp.data.User {
- String name
- boolean followed
+ String getName()
+ boolean isFollowed()
}


class com.kernelcrew.moodapp.ui.components.FilterBarFragment {
- MoodEventFilter moodEventFilter
- Set<Emotion> selectedEmotions
- OnFilterChangedListener listener
- TextInputEditText searchEditText
- MaterialButton filterEmotion
- MaterialButton filterCountAndEdit
- MaterialButton filterTimeRange
- MaterialButton filterLocation
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ MoodEventFilter getMoodEventFilter()
+ void setOnFilterChangedListener(OnFilterChangedListener)
- void notifyFilterChanged()
- void resetTime(Calendar)
}


interface com.kernelcrew.moodapp.ui.components.FilterBarFragment$OnFilterChangedListener {
~ void onFilterChanged(MoodEventFilter)
}

interface com.kernelcrew.moodapp.ui.LocationUpdateListener {
~ void onLocationUpdated(Double,Double)
}



androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.EditMoodEvent
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.components.EmotionPickerFragment
com.kernelcrew.moodapp.ui.components.EmotionPickerFragment +.. com.kernelcrew.moodapp.ui.components.EmotionPickerFragment$EmotionToggle
com.kernelcrew.moodapp.ui.components.EmotionPickerFragment +.. com.kernelcrew.moodapp.ui.components.EmotionPickerFragment$OnSelectEmotionListener
androidx.appcompat.app.AppCompatActivity <|-- com.kernelcrew.moodapp.ui.MainActivity
java.io.Serializable <|.. com.kernelcrew.moodapp.data.Comment
androidx.fragment.app.DialogFragment <|-- com.kernelcrew.moodapp.ui.DeleteDialogFragment
com.kernelcrew.moodapp.ui.DeleteDialogFragment +.. com.kernelcrew.moodapp.ui.DeleteDialogFragment$DeleteDialogListener
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.MoodHistoryAdapter
com.kernelcrew.moodapp.ui.MoodHistoryAdapter +.. com.kernelcrew.moodapp.ui.MoodHistoryAdapter$OnItemClickListener
com.kernelcrew.moodapp.ui.MoodHistoryAdapter +.. com.kernelcrew.moodapp.ui.MoodHistoryAdapter$MoodViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.MoodHistoryAdapter$MoodViewHolder
com.kernelcrew.moodapp.data.LocationHandler +.. com.kernelcrew.moodapp.data.LocationHandler$OnLocationObtainedListener
java.io.Serializable <|.. com.kernelcrew.moodapp.data.MoodEvent
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.CommentAdapter
com.kernelcrew.moodapp.ui.CommentAdapter +.. com.kernelcrew.moodapp.ui.CommentAdapter$CommentViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.CommentAdapter$CommentViewHolder
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.MyProfile
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.CreateMoodEvent
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.AuthSignUp
com.kernelcrew.moodapp.ui.AuthSignUp +.. com.kernelcrew.moodapp.ui.AuthSignUp$SignUpDetails
com.kernelcrew.moodapp.ui.AuthSignUp +.. com.kernelcrew.moodapp.ui.AuthSignUp$OnValidationCompleteListener
com.kernelcrew.moodapp.ui.AuthSignUp +.. com.kernelcrew.moodapp.ui.AuthSignUp$OnUsernameCheckListener
com.kernelcrew.moodapp.ui.OnItemSelectedListener <|.. com.kernelcrew.moodapp.ui.BottomNavBarController
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.MoodAdapter
com.kernelcrew.moodapp.ui.MoodAdapter +.. com.kernelcrew.moodapp.ui.MoodAdapter$OnMoodClickListener
com.kernelcrew.moodapp.ui.MoodAdapter +.. com.kernelcrew.moodapp.ui.MoodAdapter$MoodViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.MoodAdapter$MoodViewHolder
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.FollowRequestsFragment
com.google.android.material.bottomsheet.BottomSheetDialogFragment <|-- com.kernelcrew.moodapp.ui.components.UploadPhotoFragment
com.kernelcrew.moodapp.ui.components.UploadPhotoFragment +.. com.kernelcrew.moodapp.ui.components.UploadPhotoFragment$UploadPhotoListener
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.HomeFeed
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.FollowersFragment
com.kernelcrew.moodapp.ui.FollowersFragment +.. com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter
com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter +.. com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter$ViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.FollowersFragment$FollowersAdapter$ViewHolder
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.OtherUserProfile
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.AuthSignIn
com.kernelcrew.moodapp.ui.AuthSignIn +.. com.kernelcrew.moodapp.ui.AuthSignIn$SignInDetails
com.kernelcrew.moodapp.ui.DeleteDialogListener <|.. com.kernelcrew.moodapp.ui.MoodDetails
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.MoodDetails
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.RequestFragment
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.FollowRequestAdapter
com.kernelcrew.moodapp.ui.FollowRequestAdapter +.. com.kernelcrew.moodapp.ui.FollowRequestAdapter$ViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.FollowRequestAdapter$ViewHolder
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.LocationFragment
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.FollowingFragment
com.kernelcrew.moodapp.ui.FollowingFragment +.. com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter
com.kernelcrew.moodapp.ui.Adapter <|-- com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter
com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter +.. com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter$ViewHolder
com.kernelcrew.moodapp.ui.ViewHolder <|-- com.kernelcrew.moodapp.ui.FollowingFragment$FollowingAdapter$ViewHolder
com.kernelcrew.moodapp.ui.OnItemClickListener <|.. com.kernelcrew.moodapp.ui.MoodComments
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.MoodComments
com.kernelcrew.moodapp.ui.OnItemClickListener <|.. com.kernelcrew.moodapp.ui.MoodHistory
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.MoodHistory
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.AuthHome
com.kernelcrew.moodapp.ui.LocationUpdateListener <|.. com.kernelcrew.moodapp.ui.MoodEventForm
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.MoodEventForm
com.kernelcrew.moodapp.ui.MoodEventForm +.. com.kernelcrew.moodapp.ui.MoodEventForm$MoodEventFormSubmitCallback
com.kernelcrew.moodapp.ui.MoodEventForm +.. com.kernelcrew.moodapp.ui.MoodEventForm$MoodEventDetails
androidx.fragment.app.Fragment <|-- com.kernelcrew.moodapp.ui.components.FilterBarFragment
com.kernelcrew.moodapp.ui.components.FilterBarFragment +.. com.kernelcrew.moodapp.ui.components.FilterBarFragment$OnFilterChangedListener
@enduml