name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Perform lint check
    runs-on: ubuntu-latest
    env:
      ACTIONS: 1
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Inflate google-services.json
        run: scripts/ci.sh inflate-ci-googleservices
        env:
          ACTIONS_GOOGLESERVICES: ${{ secrets.ACTIONS_GOOGLESERVICES }}
      - name: Update Gradle Wrapper
        run: |
          cd code
          ./gradlew wrapper --gradle-version 8.5
      - name: Clean Gradle Cache
        run: |
          cd code
          ./gradlew clean
      - name: Run lint
        run: scripts/ci.sh lint
      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: code/app/build/reports/lint-results-debug.html
  unit-test:
    name: Perform Unit Testing
    runs-on: ubuntu-latest
    env:
      ACTIONS: 1
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Inflate google-services.json
        run: scripts/ci.sh inflate-ci-googleservices
        env:
          ACTIONS_GOOGLESERVICES: ${{ secrets.ACTIONS_GOOGLESERVICES }}
      - name: Update Gradle Wrapper
        run: |
          cd code
          ./gradlew wrapper --gradle-version 8.5
      - name: Clean Gradle Cache
        run: |
          cd code
          ./gradlew clean
      - name: Run tests
        run: scripts/ci.sh unit-test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: code/app/build/reports/test/testDebugUnitTest/
  instrumentation-test:
    name: Perform Instrumentation Testing
    runs-on: ubuntu-latest
    env:
      ACTIONS: 1
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Inflate google-services.json
        run: scripts/ci.sh inflate-ci-googleservices
        env:
          ACTIONS_GOOGLESERVICES: ${{ secrets.ACTIONS_GOOGLESERVICES }}
      - name: Update Gradle Wrapper
        run: |
          cd code
          ./gradlew wrapper --gradle-version 8.5
      - name: Clean Gradle Cache
        run: |
          cd code
          ./gradlew clean
      - name: Setup firebase
        run: scripts/ci.sh setup-firebaserc
        env:
          ACTIONS_FIREBASE_PROJECTID: ${{ secrets.ACTIONS_FIREBASE_PROJECTID }}
      - name: Start firebase emulators
        run: scripts/ci.sh start-firebase-emulators &
        env:
          ACTIONS_FIREBASE_TOKEN: ${{ secrets.ACTIONS_FIREBASE_TOKEN }}
      - name: Enable KVM
        run: scripts/ci.sh enable-kvm
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-build: 9322596
          script: scripts/ci.sh ui-test
          script-options: --timeout 10m
      - name: Upload Instrumentation Test report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: code/app/build/reports/androidTests/connected
  debug-apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    env:
      ACTIONS: 1
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Inflate google-services.json
        run: scripts/ci.sh inflate-ci-googleservices
        env:
          ACTIONS_GOOGLESERVICES: ${{ secrets.ACTIONS_GOOGLESERVICES }}
      - name: Update Gradle Wrapper
        run: |
          cd code
          ./gradlew wrapper --gradle-version 8.5
      - name: Clean Gradle Cache
        run: |
          cd code
          ./gradlew clean
      - name: Build debug APK
        run: scripts/ci.sh build-dbg-apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sample-app.apk
          path: code/app/build/outputs/apk/debug/app-debug.apk
